/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e718bb34ec9eb0ea62228de
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import ArticleActions from "../redux/actions/ArticleActions";

// END IMPORT ACTIONS

/** APIs

* actionsArticle.create
*	@description CRUD ACTION create
*
* actionsArticle.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsArticle.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsUser.list
*	@description CRUD ACTION list
*

**/

class ArticleEdit extends Component {
  // Init article
  constructor(props) {
    super(props);
    this.state = {
      article: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsArticle.loadArticle(this.props.match.params.id);
    }
    
    this.props.actionsUser.loadUserList();
  }

  // Insert props article in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      article: props.article
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.article._id) {
      this.props.actionsArticle.saveArticle(this.state.article).then(data => {
        this.props.history.push("/articles/");
      });
    } else {
      this.props.actionsArticle.createArticle(this.state.article).then(data => {
        this.props.history.push("/articles/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Article Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="description"
            label="Description"
            value={this.state.article.description || ""}
            onChange={Utils.handleChange.bind(this, "article")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.article.name || ""}
            onChange={Utils.handleChange.bind(this, "article")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m userId with User */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="userId">
              UserId
            </InputLabel>
            <Select
              value={this.state.article.userId || ""}
              onChange={Utils.handleChangeSelect.bind(this, "article")}
              inputProps={{
                id: "userId",
                name: "userId"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listUser && this.props.listUser.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/articles/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsArticle: bindActionCreators(ArticleActions, dispatch),
  };
};

// Validate types
ArticleEdit.propTypes = { 
  actionsArticle: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    article: state.ArticleEditReducer.article,
    listUser: state.ArticleEditReducer.listUser
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ArticleEdit);
