<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e718bb34ec9eb0ea62228de
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbTest_SK_PHP_dbManager.php';
	
/*
 * SCHEMA DB Article
 * 
	{
		description: {
			type: 'String'
		},
		name: {
			type: 'String'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		userId: {
			type: Schema.ObjectId,
			ref : "Article"
		},
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/article',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'description'	=> isset($body->description)?$body->description:'',
		'name'	=> isset($body->name)?$body->name:'',
		
		'userId' => isset($body->userId)?$body->userId:'',
	);

	$obj = makeQuery("INSERT INTO article (_id, description, name , userId )  VALUES ( null, :description, :name , :userId   )", $params, false);
    
	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/article/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM article WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/article/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM article WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/article',	function () use ($app){
	makeQuery("SELECT * FROM article");
});


//CRUD - EDIT

$app->post('/article/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'description'	    => isset($body->description)?$body->description:'',
		'name'	    => isset($body->name)?$body->name:'',
		'userId'      => isset($body->userId)?$body->userId:'' 
	);

	$obj = makeQuery("UPDATE article SET  description = :description,  name = :name  , userId=:userId  WHERE _id = :id LIMIT 1", $params, false);
    
	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>